### ISSUE TITLE
DrawerGenie 0.7 Crashes in WinUAE

### ISSUE THREAD

**Issue by Tallguy298** [daedalus2097/drawerhelper#2]
I installed DrawerGenie 0.7 in Workbench 3.2.2 with Kickstart 3.2.2 Rom using WinUAE 5.0 (64-bit).
As soon as the workbench loads, it freezes. Can't open anything. No error message or guru, just freeze.

Thank you...
Alexander.

**Comment by daedalus2097** [comment]
Yikes! I've tested it under 3.2.2 on my setup in WinUAE and it worked, but
I'll have a look right away and see if I can see what's happening. In the
meantime, if you start it manually, does it still crash?

Thanks,
    Rob

**Comment by Tallguy298** [comment]
I tested this morning on my Amiga 600 and the same result, still crashes.
I rebooted into failsafe mode and ran the program manually and it still crashes.
I am currently running version 0.4 and works perfectly.

Alex.

**Comment by daedalus2097** [comment]
I'm very sorry about that, and hopefully I'll get to the bottom of it very
quickly. Would it be possible for you to run SnoopDOS first to see if it's
freezing on a particular operation? Also, were you using the previous
version (0.4)? If not, would you mind trying it for me to see if it works?

Thanks,
    Rob

**Comment by Tallguy298** [comment]
I can SnoopDOS and could not see the error quickly enough.
As soon as I ran DrawerGenie the Amiga crashed immediately.

Regards,
Alex.

**Comment by daedalus2097** [comment]
Hi Alex,
    I've just had another report of a crash on startup, and it may be
related to the settings pointing to the old toolbar image. In the
DrawerGenie directory, there's a subdirectory for toolbars. If you make a
copy of default.iff in the main DrawerGenie directory, that might solve the
problem.

It's supposed to handle this situation properly but something's gone wrong
along the way. I'll check it out tonight :)

Thanks,
    Rob

**Comment by Tallguy298** [comment]
Hi Rob,

I got the program working by copying the default.iff file into the toolbars directory renaming it toolbar.iff.
Works fine without crashing.

Thank you.

**Comment by Channel-Zx** [comment]
Same issue as above I did a clean install remove previous version and ran installer.
Running from tools/commodities drawer and HOMEDIR set correctly. 
I get a freeze after a while and then a black screen.
I have an ASSIGN called Tools: pointing to sys:tools.
Here's SnoopDOS log.

SnoopDos logging started on Thursday, 19-Sep-24 at 17:58:03

 Count Process Name       Action     Target Name                 Options Res.
 ----- ------------       ------     -----------                 ------- ----
SnoopDos enabled  at 17:58:03
 1     DrawerGenie        FindPort   Directory Opus                      Fail
 2     ramlib             Load       LIBS:newicon.library                Fail
 3     ramlib             Load       HD0:Tools/Commodities/newic         Fail
 4     DrawerGenie        OpenLib    newicon.library             Ver 0   Fail
 5     ramlib             GetVar     WIZARDSTYLE                 Any     Fail
 6     ramlib             GetVar     WIZARDBUBBLEHELPDELAY       Any     Fail
 7     DrawerGenie        FindPort   Directory Opus                      Fail
 8     DrawerGenie        Open       Tools:DrawerGenie/Toolbars/ Read    Fail
 9     DrawerGenie        Open       Tools:DrawerGenie/Toolbars/ Read    Fail
 10    DrawerGenie        Open       Tools:DrawerGenie/Toolbars/ Read    Fail
 11    DrawerGenie        Open       Tools:DrawerGenie/Toolbars/ Read    Fail
 12    DrawerGenie        Open       Tools:DrawerGenie/Toolbars/ Read    Fail

Closed SnoopDos log at 17:59:18 

Also tried changing the name for the homedir to SYS:Tools/DrawerGenie and no change. 
I changed the path in the icons tool types > SYS:Tools/DrawerGenie/Toolbars/ and i got a popup so I pointed it to the toolbars drawer and I got the error.

"ERROR - Files could not be found Please quit and try again"

looks like it can't read the toolbars drawer or contents ?
I can open the 3 .iff files in Multiview.

**Comment by Tallguy298** [comment]
Channel Z I got the program working.
1) Install as normal.
2) In the Toolbars directory delete all the files but default.iff.
3) Rename the default.iff to toolbar.iff and reboot.
If done properly the toolbar.iff file should be 3782 bytes.

Opening the preferences screen should give you this...
![Prefs](https://github.com/user-attachments/assets/9a11671a-b15c-4d9c-bd0c-97a3928d8550)

The dropdown toolbar menu should look like this...
![ToolBar](https://github.com/user-attachments/assets/854fc060-10df-4d2f-9793-d0ec8944c448)

To fix the problem, modify the installer and rename the files.

Thank you...

**Comment by Channel-Zx** [comment]
I followed your instructions and no luck on my main OS image.
Decided to fired up a vanilla OS3221 base install and ran though above instructions and it throws an error.
Also checked that toolbar.iff opens in Multiview.

<img width="1180" alt="1" src="https://github.com/user-attachments/assets/1f6c54df-11d2-4fb4-8f6c-c31a543624f3">

**Comment by Tallguy298** [comment]
Channel Z, it looks like you might be missing some libraries?

Here is a complete list of the libraries used by this program with the versions installed on my system.
- asl.library 47.9
- datatypes.library.47.3
- commodities.library 45.2
- cybergraphics.library 42.7   http://aminet.net/driver/video/CGraphX224u.lha
- diskfont.library  47.1
- dos.library 47.3
- exec.library 47.1
- gadtools.library 47.17
- graphics.library 47.1
- mathffp.library 46.1
- icon.library 51.4.587   http://aminet.net/util/libs/IconLib_46.4.lha
- intuition.library 47.52
- jpeg.library 6.2   http://aminet.net/util/libs/jpeglibrary.lha
- layers.library 46.2
- locale.library 47.3
- newicon.library 44.0   http://aminet.net/util/libs/NewIconEmu.lha
- mathtrans.library 47.1
- rexxsyslib.library 47.2
- wbstart.library 2.0
- wizard.library 42.100   http://aminet.net/util/libs/WizardLibrary.lha
- workbench.library 47.37
- zlib.library 3.2   http://aminet.net/util/libs/zlib-library.lha

Secondly if you installed the program to automatically start from the WBStartup directory, then the tooltypes should look like this...
![Info](https://github.com/user-attachments/assets/1a82539c-43bb-48b0-9fda-bfe54d162134)
The tooltype HOMEDIR should point to the directory where the other executables and icons are located.

I hope this helps?
Regards, Alex.

**Comment by daedalus2097** [comment]
Sorry both, it looks like there are two separate issues with this release that I didn't catch because I clearly didn't do enough testing.

First issue: Extra dependencies were introduced in this version (jpeg.library and zlib.library), and DrawerGenie will crash if they're not present (even if they're not used - they're only needed for loading PNG or JPEG toolbar files). This will be fixed to use datatypes instead.


Second issue: The toolbar can't be found because the location of the toolbar has changed from the location in the previous release. The code is supposed to take this into account, but it sometimes doesn't, seemingly depending on certain settings. this will be fixed shortly too.

Thanks for the reports, and apologies!
