### ISSUE TITLE
Copy files error in installer

### ISSUE THREAD

**Issue by Tallguy298** [daedalus2097/drawerhelper#3]
Using your current installer version 0.8 crashes on line 78.

Changing the lines fixes the problem...

`(complete 80)`
`; `
`(copyfiles`
`  (prompt "Copying DrawerGenie to WBStartup...")`
`  (help @copyfiles-help)`
`  (infos)`
`  (source @default-dest)`
`  (dest "SYS:WBStartup")`
`  (choices "DrawerGenie")`
`)`

Regards,
Alex.

**Comment by daedalus2097** [comment]
Aw man, sorry about that. I somehow managed to do the last compile of the
script with an old version of InstallerGen (and then didn't test the
WBStartup option). Hotfix incoming!

Thanks,
    Rob
